# ai_module/ai_service.py

from chat.models import Conversation, Message

def generate_ai_reply(conversation_id):
    """
    Mock AI reply generator – replace with LLM API call later.
    """
    conversation = Conversation.objects.get(id=conversation_id)
    last_message = Message.objects.filter(conversation=conversation, sender='user').last()
    if last_message:
        return f"AI Response to: '{last_message.content}'"
    return "Hello! How can I assist you today?"


def analyze_conversation(conversation_id):
    """
    Mock analysis after conversation ends.
    """
    conversation = Conversation.objects.get(id=conversation_id)
    conversation.summary = "Conversation summary generated by AI."
    conversation.topic_keywords = ["example", "keyword"]
    conversation.sentiment = "Neutral"
    conversation.action_items = ["Follow up tomorrow"]
    conversation.save()
    return conversation.summary


def query_past_conversations(query, filters=None):
    """
    Simple keyword-based search for now.
    Later, can integrate embeddings or pgvector.
    """
    qs = Message.objects.filter(content__icontains=query).select_related('conversation')

    if filters and "date_range" in filters:
        start, end = filters["date_range"]
        qs = qs.filter(conversation__start_time__range=[start, end])

    # Build sources for the response
    sources = []
    for msg in qs[:5]:
        sources.append({
            "conversation_id": str(msg.conversation.id),
            "excerpt": msg.content
        })

    # Mock answer generation
    answer = f"I found {len(sources)} related messages for your query '{query}'."

    return answer, sources
